# Listener capable of handling KNX bus messages provided through a KNX-IP Interface.
[[inputs.knx_listener]]
## Type of KNX-IP interface.
## Can be either "tunnel" or "router".
service_type = "router"

## Address of the KNX-IP interface.
service_address = "224.0.23.12:3671"

## Measurement definition(s)
[[inputs.knx_listener.measurement]]
## Name of the measurement
name = "temperature"
## Datapoint-Type (DPT) of the KNX messages
dpt = "9.001"
## List of Group-Addresses (GAs) assigned to the measurement
addresses = ["5/5/1"]
